# Generated by Django 5.1.3 on 2024-11-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_conges_status_alter_conges_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conges',
            old_name='status',
            new_name='validate',
        ),
    ]
